'use strict';
const days=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
const $=id=>document.getElementById(id);
const state=days.map(()=>({selected:false,start:'',end:'',allDay:false}));
const form=$('coverage-form');
const format=t=>{if(!t)return '';const [h,m]=t.split(':').map(Number);return `${h%12||12}:${String(m).padStart(2,'0')} ${h<12?'a.m.':'p.m.'}`;};
const hours=s=>s.allDay?'24 hours':(!s.start||!s.end?'Hours not set':`${format(s.start)} – ${format(s.end)}${s.end<s.start?' (next day)':''}`);
function hideReview(){}
function snapshot(){const selected=state.flatMap((s,i)=>s.selected?[`${days[i].slice(0,3)}  ${hours(s)}`]:[]);let zone=$('timezone').value==='other'?$('other-zone').value:$('timezone').selectedOptions[0].textContent;$('snapshot').textContent=selected.length?selected.join('\n')+($('timezone').value?'\n\n'+zone:''):'Your selected days and hours will appear here.';}
function updateNote(i){const s=state[i],note=$(`note-${i}`);if(s.allDay)note.textContent='Full 24-hour coverage beginning on this day.';else if(s.start&&s.end&&s.start===s.end)note.textContent='Choose different times, or select 24 hours.';else if(s.start&&s.end&&s.end<s.start)note.textContent=`Ends ${days[(i+1)%7]} at ${format(s.end)} (next day).`;else note.textContent=s.start&&s.end?'Same-day coverage.':'Enter both times or apply common hours above.';}
function render(){const host=$('schedule-rows');host.replaceChildren();state.forEach((s,i)=>{if(!s.selected)return;const row=document.createElement('div');row.className='schedule-row';row.innerHTML=`<div class="row-day">${days[i]}</div><label for="start-${i}">Start<input id="start-${i}" type="time" aria-label="${days[i]} start time"></label><label for="end-${i}">End<input id="end-${i}" type="time" aria-label="${days[i]} end time"></label><label class="checkline"><input id="all-${i}" type="checkbox" aria-label="${days[i]} 24-hour coverage">24 hours</label><p class="row-note" id="note-${i}"></p>`;host.append(row);for(const key of ['start','end']){const input=$(`${key}-${i}`);input.value=s[key];input.disabled=s.allDay;input.required=!s.allDay;input.setAttribute('aria-describedby',`note-${i}`);input.addEventListener('input',()=>{s[key]=input.value;updateNote(i);snapshot();hideReview();});}$(`all-${i}`).checked=s.allDay;$(`all-${i}`).addEventListener('change',e=>{s.allDay=e.target.checked;for(const key of ['start','end']){$(`${key}-${i}`).disabled=s.allDay;$(`${key}-${i}`).required=!s.allDay;}updateNote(i);snapshot();hideReview();});updateNote(i);});$('empty-schedule').hidden=state.some(s=>s.selected);$('apply').disabled=!state.some(s=>s.selected);snapshot();hideReview();}
days.forEach((day,i)=>{const label=document.createElement('label');label.className='day';label.innerHTML=`<input type="checkbox" id="day-${i}" aria-label="${day}"><span aria-hidden="true">${day.slice(0,3)}</span>`;$('day-picker').append(label);$(`day-${i}`).addEventListener('change',e=>{state[i].selected=e.target.checked;render();});});
for(const [id,predicate]of [['weekdays',i=>i<5],['everyday',()=>true],['clear',()=>false]])$(id).addEventListener('click',()=>{state.forEach((s,i)=>{s.selected=predicate(i);$(`day-${i}`).checked=s.selected;});render();});
$('apply').addEventListener('click',()=>{const a=$('shared-start'),b=$('shared-end');if(!a.value||!b.value){(a.value?b:a).focus();$('schedule-status').textContent='Enter both common times before applying.';return;}state.forEach(s=>{if(s.selected){s.start=a.value;s.end=b.value;s.allDay=false;}});render();$('schedule-status').textContent=`Applied ${format(a.value)} to ${format(b.value)} to all selected days.`;});
$('timezone').addEventListener('change',()=>{const other=$('timezone').value==='other';$('other-zone-wrap').hidden=!other;$('other-zone').disabled=!other;$('other-zone').required=other;snapshot();});$('other-zone').addEventListener('input',snapshot);
$('unsure').addEventListener('change',()=>{$('cases').disabled=$('unsure').checked;$('cases').required=!$('unsure').checked;$('cases').removeAttribute('aria-invalid');});
form.addEventListener('input',hideReview);form.addEventListener('change',hideReview);
function validate(){const errors=[];form.querySelectorAll('[aria-invalid]').forEach(el=>el.removeAttribute('aria-invalid'));const add=(id,message)=>{errors.push({id,message});$(id).setAttribute('aria-invalid','true');};for(const [id,label]of [['fullName','Enter your first and last name.'],['organization','Enter your group or hospital.']])if(!$(id).value.trim())add(id,label);if(!$('email').value.trim()||!$('email').validity.valid)add('email','Enter a valid email address.');if(!state.some(s=>s.selected))add('day-0','Select at least one day of coverage.');state.forEach((s,i)=>{if(!s.selected||s.allDay)return;if(!s.start)add(`start-${i}`,`Enter a start time for ${days[i]}.`);if(!s.end)add(`end-${i}`,`Enter an end time for ${days[i]}.`);if(s.start&&s.start===s.end)add(`end-${i}`,`For ${days[i]}, use different times or select 24 hours.`);});if(!$('timezone').value)add('timezone','Select your hospital’s time zone.');if($('timezone').value==='other'&&!$('other-zone').value.trim())add('other-zone','Specify your time zone.');if(!$('unsure').checked&&(!$('cases').value||!$('cases').validity.valid))add('cases','Enter a whole number of daily cases (0 or more), or select “I’m not sure yet.”');return errors;}
form.addEventListener('submit',e=>{e.preventDefault();const errors=validate();$('errors').replaceChildren();if(errors.length){$('errors').hidden=false;const title=document.createElement('strong');title.textContent='A few details still need your attention.';$('errors').append(title);const list=document.createElement('ul');errors.forEach(({id,message})=>{const li=document.createElement('li'),a=document.createElement('a');a.href='#'+id;a.textContent=message;a.addEventListener('click',e=>{e.preventDefault();$(id).focus();});li.append(a);list.append(li);});$('errors').append(list);$('errors').focus();return;}$('errors').hidden=true;
const draft={version:1,fields:Object.fromEntries(new FormData(form)),schedule:state,timezoneLabel:$('timezone').value==='other'?$('other-zone').value.trim():$('timezone').selectedOptions[0].textContent,unsure:$('unsure').checked,sharedStart:$('shared-start').value,sharedEnd:$('shared-end').value,cases:$('cases').value};
try{sessionStorage.setItem('atr-coverage-draft',JSON.stringify(draft));location.href='confirm-coverage.html';}catch{ $('errors').hidden=false;$('errors').textContent='Your browser could not keep your answers for the review page. Allow session storage and try again. Your entries are still here.';$('errors').focus();}
});
try{const draft=JSON.parse(sessionStorage.getItem('atr-coverage-draft'));if(draft?.version===1&&Array.isArray(draft.schedule)&&draft.schedule.length===7){for(const [name,value]of Object.entries(draft.fields)){const field=form.elements.namedItem(name);if(field&&field.type!=='checkbox')field.value=value;}draft.schedule.forEach((s,i)=>{Object.assign(state[i],s);$('day-'+i).checked=s.selected;});$('shared-start').value=draft.sharedStart;$('shared-end').value=draft.sharedEnd;$('unsure').checked=draft.unsure;$('cases').value=draft.cases;$('unsure').dispatchEvent(new Event('change'));$('timezone').dispatchEvent(new Event('change'));}}catch{}
render();$('review-button').disabled=false;
