'use strict';
const days=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
const $=id=>document.getElementById(id);
const state=days.map(()=>({selected:false,start:'',end:'',frequency:'weekly',allDay:false}));
const form=$('coverage-form');
const format=t=>{if(!t)return '';const [h,m]=t.split(':').map(Number);return `${h%12||12}:${String(m).padStart(2,'0')} ${h<12?'a.m.':'p.m.'}`;};
const hours=s=>s.allDay?'24 hours':(!s.start||!s.end?'Hours not set':`${format(s.start)} – ${format(s.end)}${s.end<s.start?' (next day)':''}`);
function hideReview(){}
const frequencyLabel=s=>s.frequency==='weekly'?'Every week':`${s.frequency} ${s.frequency==='1'?'shift':'shifts'} per month`;
function snapshot(){const selected=state.flatMap((s,i)=>s.selected?[`${days[i].slice(0,3)}  ${hours(s)} · ${frequencyLabel(s)}`]:[]);let zone=$('timezone').value==='other'?$('other-zone').value:$('timezone').selectedOptions[0].textContent;$('snapshot').textContent=selected.length?selected.join('\n')+($('timezone').value?'\n\n'+zone:''):'Your selected days and hours will appear here.';}
function updateNote(i){const s=state[i],note=$(`note-${i}`);if(s.allDay)note.textContent='Full 24-hour coverage beginning on this day.';else if(s.start&&s.end&&s.start===s.end)note.textContent='Choose different start and end times.';else if(s.start&&s.end&&s.end<s.start)note.textContent=`Ends ${days[(i+1)%7]} at ${format(s.end)} (next day).`;else note.textContent=s.start&&s.end?'Same-day coverage.':'Enter both times or apply common hours above.';}
function render(){const host=$('schedule-rows');host.replaceChildren();state.forEach((s,i)=>{if(!s.selected)return;const row=document.createElement('div');row.className='schedule-row';row.innerHTML=`<div class="row-day">${days[i]}</div><label for="start-${i}">Start<input id="start-${i}" type="time" aria-label="${days[i]} start time"></label><label for="end-${i}">End<input id="end-${i}" type="time" aria-label="${days[i]} end time"></label><label class="shift-frequency" for="frequency-${i}">Frequency<select id="frequency-${i}" aria-label="${days[i]} shift frequency"><option value="weekly">Every week</option><option value="1">1 per month</option><option value="2">2 per month</option><option value="3">3 per month</option><option value="4">4 per month</option><option value="5">5 per month</option></select></label><p class="row-note" id="note-${i}"></p>`;host.append(row);for(const key of ['start','end']){const input=$(`${key}-${i}`);input.value=s[key];input.disabled=s.allDay;input.required=!s.allDay;input.setAttribute('aria-describedby',`note-${i}`);input.addEventListener('input',()=>{s[key]=input.value;updateNote(i);snapshot();hideReview();});}$(`frequency-${i}`).value=s.frequency;$(`frequency-${i}`).addEventListener('change',e=>{s.frequency=e.target.value;snapshot();});updateNote(i);});$('empty-schedule').hidden=state.some(s=>s.selected);$('apply').disabled=!state.some(s=>s.selected);snapshot();hideReview();}
days.forEach((day,i)=>{const label=document.createElement('label');label.className='day';label.innerHTML=`<input type="checkbox" id="day-${i}" aria-label="${day}"><span aria-hidden="true">${day.slice(0,3)}</span>`;$('day-picker').append(label);$(`day-${i}`).addEventListener('change',e=>{state[i].selected=e.target.checked;render();});});
for(const [id,predicate]of [['weekdays',i=>i<5],['everyday',()=>true],['clear',()=>false]])$(id).addEventListener('click',()=>{state.forEach((s,i)=>{s.selected=predicate(i);$(`day-${i}`).checked=s.selected;});render();});
$('apply').addEventListener('click',()=>{const a=$('shared-start'),b=$('shared-end');if(!a.value||!b.value){(a.value?b:a).focus();$('schedule-status').textContent='Enter both common times before applying.';return;}state.forEach(s=>{if(s.selected){s.start=a.value;s.end=b.value;s.allDay=false;}});render();$('schedule-status').textContent=`Applied ${format(a.value)} to ${format(b.value)} to all selected days.`;});
$('timezone').addEventListener('change',()=>{const other=$('timezone').value==='other';$('other-zone-wrap').hidden=!other;$('other-zone').disabled=!other;$('other-zone').required=other;snapshot();});$('other-zone').addEventListener('input',snapshot);
form.addEventListener('input',hideReview);form.addEventListener('change',hideReview);
function validate(){const errors=[];form.querySelectorAll('[aria-invalid]').forEach(el=>el.removeAttribute('aria-invalid'));const add=(id,message)=>{errors.push({id,message});$(id).setAttribute('aria-invalid','true');};for(const [id,label]of [['fullName','Enter your first and last name.']])if(!$(id).value.trim())add(id,label);if(!$('email').value.trim()||!$('email').validity.valid)add('email','Enter a valid email address.');if(!state.some(s=>s.selected))add('day-0','Select at least one preferred reading day.');state.forEach((s,i)=>{if(!s.selected||s.allDay)return;if(!s.start)add(`start-${i}`,`Enter a start time for ${days[i]}.`);if(!s.end)add(`end-${i}`,`Enter an end time for ${days[i]}.`);if(s.start&&s.start===s.end)add(`end-${i}`,`For ${days[i]}, use different start and end times.`);});if(!$('timezone').value)add('timezone','Select your preferred schedule’s time zone.');if($('timezone').value==='other'&&!$('other-zone').value.trim())add('other-zone','Specify your time zone.');if(!attachedCV)add('cv','Attach your Resume as a PDF, DOC, or DOCX (up to 10 MB).');return errors;}
let attachedCV=null;
const draftKey='atr-radiologist-draft';
const cvKey='atr-radiologist-cv-id';
function cvDatabase(){return new Promise((resolve,reject)=>{const req=indexedDB.open('atr-application-preview',1);req.onupgradeneeded=()=>req.result.createObjectStore('cvs');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});}
async function cvOperation(mode,id,file){const db=await cvDatabase();return new Promise((resolve,reject)=>{const tx=db.transaction('cvs',mode==='get'?'readonly':'readwrite');const store=tx.objectStore('cvs');let request=mode==='get'?store.get(id):mode==='delete'?store.delete(id):store.put(file,id);let result;request.onsuccess=()=>{result=request.result;};tx.oncomplete=()=>{db.close();resolve(result);};tx.onerror=()=>{db.close();reject(tx.error);};});}
function showCV(){ $('cv-status').textContent=attachedCV?`${attachedCV.name} · ${(attachedCV.size/1024/1024).toFixed(2)} MB · Attached for review`:'No Resume attached.';$('remove-cv').hidden=!attachedCV; }
$('cv').addEventListener('change',async()=>{const file=$('cv').files[0];if(!file)return;if(!/\.(pdf|doc|docx)$/i.test(file.name)||file.size>10*1024*1024||file.size===0){$('cv').value='';attachedCV=null;$('remove-cv').hidden=false;$('cv-status').textContent='Choose a non-empty PDF, DOC, or DOCX file no larger than 10 MB.';$('cv').setAttribute('aria-invalid','true');return;}attachedCV=file;$('cv').removeAttribute('aria-invalid');showCV();});
$('remove-cv').addEventListener('click',async()=>{try{const id=sessionStorage.getItem(cvKey);if(id)await cvOperation('delete',id);sessionStorage.removeItem(cvKey);attachedCV=null;$('cv').value='';showCV();}catch{$('cv-status').textContent='Could not remove the saved Resume. Please try again.';}});
form.addEventListener('submit',async e=>{e.preventDefault();const errors=validate();$('errors').replaceChildren();if(errors.length){$('errors').hidden=false;const title=document.createElement('strong');title.textContent='A few details still need your attention.';const list=document.createElement('ul');errors.forEach(({id,message})=>{const li=document.createElement('li'),a=document.createElement('a');a.href='#'+id;a.textContent=message;a.addEventListener('click',ev=>{ev.preventDefault();$(id).focus();});li.append(a);list.append(li);});$('errors').append(title,list);$('errors').focus();return;}$('errors').hidden=true;$('review-button').disabled=true;try{const id=sessionStorage.getItem(cvKey)||crypto.randomUUID();await cvOperation('put',id,attachedCV);sessionStorage.setItem(cvKey,id);const draft={version:1,fields:Object.fromEntries(new FormData(form)),schedule:state,timezoneLabel:$('timezone').value==='other'?$('other-zone').value.trim():$('timezone').selectedOptions[0].textContent,sharedStart:$('shared-start').value,sharedEnd:$('shared-end').value,cv:{name:attachedCV.name,size:attachedCV.size}};sessionStorage.setItem(draftKey,JSON.stringify(draft));location.href='review-radiologist.html';}catch{$('errors').hidden=false;$('errors').textContent='Your browser could not keep the application and Resume for review. Allow browser storage and try again. Your entries are still here.';$('errors').focus();$('review-button').disabled=false;}});
async function restore(){try{const draft=JSON.parse(sessionStorage.getItem(draftKey));if(draft?.version===1&&draft.schedule?.length===7){for(const [name,value]of Object.entries(draft.fields)){const field=form.elements.namedItem(name);if(field&&field.type!=='file')field.value=value;}draft.schedule.forEach((s,i)=>{Object.assign(state[i],s);$('day-'+i).checked=s.selected;});$('shared-start').value=draft.sharedStart;$('shared-end').value=draft.sharedEnd;$('timezone').dispatchEvent(new Event('change'));const id=sessionStorage.getItem(cvKey);if(id)attachedCV=await cvOperation('get',id);showCV();}}catch{$('cv-status').textContent='Please attach your Resume again to continue.';}render();$('review-button').disabled=false;}
restore();
